//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARIA_QUERY
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldSpecificTargetParameter
    {
        public long FieldSpecificTargetParametersSer { get; set; }
        public Nullable<long> PlanSetupSer { get; set; }
        public Nullable<long> StructureSer { get; set; }
        public Nullable<long> BaseStructureSer { get; set; }
        public int SetupErrorSymmetricFlag { get; set; }
        public Nullable<double> SetupErrorX1 { get; set; }
        public Nullable<double> SetupErrorX2 { get; set; }
        public Nullable<double> SetupErrorY1 { get; set; }
        public Nullable<double> SetupErrorY2 { get; set; }
        public Nullable<double> SetupErrorZ1 { get; set; }
        public Nullable<double> SetupErrorZ2 { get; set; }
        public int InternalTargetMotionSymmetricFlag { get; set; }
        public Nullable<double> InternalTargetMotionX1 { get; set; }
        public Nullable<double> InternalTargetMotionX2 { get; set; }
        public Nullable<double> InternalTargetMotionY1 { get; set; }
        public Nullable<double> InternalTargetMotionY2 { get; set; }
        public Nullable<double> InternalTargetMotionZ1 { get; set; }
        public Nullable<double> InternalTargetMotionZ2 { get; set; }
        public int SmearingMarginOverrideFlag { get; set; }
        public int SmearingMarginSymmetricFlag { get; set; }
        public Nullable<double> SmearingMarginX1 { get; set; }
        public Nullable<double> SmearingMarginX2 { get; set; }
        public Nullable<double> SmearingMarginY1 { get; set; }
        public Nullable<double> SmearingMarginY2 { get; set; }
        public Nullable<double> RangeUncertaintyPercentage { get; set; }
        public Nullable<double> ProximalSafetyMargin { get; set; }
        public Nullable<double> DistalSafetyMargin { get; set; }
        public Nullable<double> GantryRtn { get; set; }
        public Nullable<double> PatientSupportAngle { get; set; }
        public Nullable<double> IsoCenterX { get; set; }
        public Nullable<double> IsoCenterY { get; set; }
        public Nullable<double> IsoCenterZ { get; set; }
        public Nullable<double> SAD { get; set; }
        public string PlanTreatmentOrientation { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual Structure Structure { get; set; }
        public virtual PlanSetup PlanSetup { get; set; }
        public virtual Structure Structure1 { get; set; }
    }
}
